In [38]:
import pandas as pd
import pyodbc

In [23]:
server = r'DESKTOP-5KQL2U6\MSSQLSERVER01'
database = 'Python'
conexaoDB = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};'
                           f'SERVER={server};'
                           f'DATABASE={database};'
                           'Trusted_Connection=yes;')

cursor = conexaoDB.cursor()

In [37]:
cursor.close()

In [24]:
query = """

select * from [dbo].[Parte3]
where Estoque > 40

"""

In [ ]:
estoque = pd.read_sql(query, conexaoDB)

estoque.head(10)

#### CRIAR CONEXÃO COM OUTRO BANCO DE DADOS/SERVIDOR

In [26]:
server2 = r'DESKTOP-5KQL2U6\MSSQLSERVER01'
database2 = 'Python2'
conexaoDB2 = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};'
                           f'SERVER={server2};'
                           f'DATABASE={database2};'
                           'Trusted_Connection=yes;')

cursor2 = conexaoDB2.cursor()

In [27]:
query2 = '''

select * from [dbo].[Mercado]

'''

In [ ]:
produtos = pd.read_sql(query2, conexaoDB2)

In [31]:
estoque.head(5)

   ID  Estoque    Validade
0   1       50  2024-12-01
1   3       60  2025-03-10
2   5       45  2025-01-05
3   6      100  2025-08-15
4   7       70  2024-11-30

In [34]:
produtos.head(5)

,Produtos,Categoria,Preco,ID,Marca,Estoque,Fornecedor,Preco_Por_Unidade,Origem,Peso,Validade
0,Arroz,Alimentos,22.9,1,Tio João,50,Distribuidora XYZ,"2,29 (kg)",Nacional,5 kg,2024-12-01
1,Feijão,Alimentos,8.5,2,Camil,40,Atacado Central,"4,25 (kg)",Nacional,1 kg,2024-11-15
2,Açúcar,Alimentos,4.3,3,União,60,Distribuidora ABC,"4,30 (kg)",Nacional,1 kg,2025-03-10
3,Farinha de trigo,Alimentos,5.6,4,Dona Benta,35,Atacado Central,"2,80 (kg)",Nacional,1 kg,2025-04-20
4,Óleo de soja,Alimentos,9.8,5,Liza,45,Distribuidora XYZ,"9,80 (litro)",Nacional,900 ml,2025-01-05

In [35]:
join = pd.merge(estoque, produtos, left_on='ID', right_on='ID', how='left')

In [36]:
join

,ID,Estoque_x,Validade_x,Produtos,Categoria,Preco,Marca,Estoque_y,Fornecedor,Preco_Por_Unidade,Origem,Peso,Validade_y
0,1,50,2024-12-01,Arroz,Alimentos,22.9,Tio João,50,Distribuidora XYZ,"2,29 (kg)",Nacional,5 kg,2024-12-01
1,3,60,2025-03-10,Açúcar,Alimentos,4.3,União,60,Distribuidora ABC,"4,30 (kg)",Nacional,1 kg,2025-03-10
2,5,45,2025-01-05,Óleo de soja,Alimentos,9.8,Liza,45,Distribuidora XYZ,"9,80 (litro)",Nacional,900 ml,2025-01-05
3,6,100,2025-08-15,Sal,Alimentos,2.5,Cisne,100,Atacado Alimentos,"2,50 (kg)",Nacional,1 kg,2025-08-15
4,7,70,2024-11-30,Macarrão,Alimentos,4.2,Renata,70,Distribuidora ABC,"2,10 (kg)",Nacional,500 g,2024-11-30
5,13,50,2024-12-15,Pão de forma,Alimentos,6.5,Pullman,50,Distribuidora Pães LTDA,"6,50 (500g)",Nacional,500 g,2024-12-15
6,14,80,2025-03-01,Biscoito de água e sal,Alimentos,3.2,Marilan,80,Atacado Alimentos,"16,00 (kg)",Nacional,200 g,2025-03-01
7,15,60,2025-10-20,Achocolatado em pó,Alimentos,8.9,Nescau,60,Fornecedor Bebidas LTDA,"8,90 (400g)",Nacional,400 g,2025-10-20
8,16,90,2025-07-30,Molho de tomate,Alimentos,3.9,Elefante,90,Distribuidora Molhos LTDA,"7,80 (340g)",Nacional,340 g,2025-07-30
9,20,100,2025-03-01,Detergente líquido,Higiene,3.5,Ypê,100,Atacado Higiene,"3,50 (litro)",Nacional,500 ml,2025-03-01
10,21,200,2025-04-15,Papel higiênico,Higiene,12.0,Neve,200,Atacado Higiene,"1,50 (rolo)",Nacional,4 rolos,2025-04-15
11,22,150,2025-06-20,Sabonete,Higiene,2.8,Lux,150,Distribuidora Higiene LTDA,"2,80 (unidade)",Nacional,90 g,2025-06-20
12,23,60,2025-05-05,Shampoo,Higiene,9.4,Palmolive,60,Fornecedor Beleza LTDA,"9,40 (litro)",Nacional,325 ml,2025-05-05
13,25,75,2025-11-01,Desodorante,Higiene,7.2,Pantene,75,Distribuidora Beleza LTDA,"7,20 (unidade)",Nacional,150 ml,2025-11-01
14,26,120,2025-07-01,Água mineral,Bebidas,1.8,Rexona,120,Atacado Bebidas LTDA,"0,90 (litro)",Nacional,500 ml,2025-07-01
15,30,150,2025-09-15,Ovo,Alimentos,14.0,Kellogg's,150,Fornecedor Ovos LTDA,"0,47 (unidade)",Nacional,30 unidades,2025-09-15

In [ ]:
cursor.close()